// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Decrementer$ReactTemplate = require("./Decrementer.bs.js");
var Incrementer$ReactTemplate = require("./Incrementer.bs.js");

var counter = ReasonReact.statelessComponent("Counter");

function make() {
  return /* record */[
          /* debugName */counter[/* debugName */0],
          /* reactClassInternal */counter[/* reactClassInternal */1],
          /* handedOffState */counter[/* handedOffState */2],
          /* willReceiveProps */counter[/* willReceiveProps */3],
          /* didMount */counter[/* didMount */4],
          /* didUpdate */counter[/* didUpdate */5],
          /* willUnmount */counter[/* willUnmount */6],
          /* willUpdate */counter[/* willUpdate */7],
          /* shouldUpdate */counter[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "container jumbotron"
                        }, React.createElement("div", {
                              className: "row"
                            }, React.createElement("div", {
                                  className: "md-12 mx-auto"
                                }, React.createElement("center", undefined, React.createElement("h1", undefined, "This is a simple counter")))), React.createElement("div", {
                              className: "row md-5"
                            }), React.createElement("div", {
                              className: "row"
                            }, React.createElement("div", {
                                  className: "col-md-3"
                                }, ReasonReact.element(/* None */0, /* None */0, Decrementer$ReactTemplate.make(/* array */[]))), React.createElement("div", {
                                  className: "col-md-6"
                                }, React.createElement("center", undefined, React.createElement("h1", undefined, "0"))), React.createElement("div", {
                                  className: "col-md-3"
                                }, ReasonReact.element(/* None */0, /* None */0, Incrementer$ReactTemplate.make(/* array */[])))));
            }),
          /* initialState */counter[/* initialState */10],
          /* retainedProps */counter[/* retainedProps */11],
          /* reducer */counter[/* reducer */12],
          /* subscriptions */counter[/* subscriptions */13],
          /* jsElementWrapped */counter[/* jsElementWrapped */14]
        ];
}

exports.counter = counter;
exports.make = make;
/* counter Not a pure module */
