// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var decrementer = ReasonReact.statelessComponent("Decrementer");

function make() {
  return /* record */[
          /* debugName */decrementer[/* debugName */0],
          /* reactClassInternal */decrementer[/* reactClassInternal */1],
          /* handedOffState */decrementer[/* handedOffState */2],
          /* willReceiveProps */decrementer[/* willReceiveProps */3],
          /* didMount */decrementer[/* didMount */4],
          /* didUpdate */decrementer[/* didUpdate */5],
          /* willUnmount */decrementer[/* willUnmount */6],
          /* willUpdate */decrementer[/* willUpdate */7],
          /* shouldUpdate */decrementer[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("button", {
                          className: "btn btn-danger btn-block"
                        }, "-");
            }),
          /* initialState */decrementer[/* initialState */10],
          /* retainedProps */decrementer[/* retainedProps */11],
          /* reducer */decrementer[/* reducer */12],
          /* subscriptions */decrementer[/* subscriptions */13],
          /* jsElementWrapped */decrementer[/* jsElementWrapped */14]
        ];
}

exports.decrementer = decrementer;
exports.make = make;
/* decrementer Not a pure module */
