// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Decrementer$ReactTemplate = require("./Decrementer.bs.js");
var Incrementer$ReactTemplate = require("./Incrementer.bs.js");

var counter = ReasonReact.reducerComponent("Counter");

function make() {
  return /* record */[
          /* debugName */counter[/* debugName */0],
          /* reactClassInternal */counter[/* reactClassInternal */1],
          /* handedOffState */counter[/* handedOffState */2],
          /* willReceiveProps */counter[/* willReceiveProps */3],
          /* didMount */counter[/* didMount */4],
          /* didUpdate */counter[/* didUpdate */5],
          /* willUnmount */counter[/* willUnmount */6],
          /* willUpdate */counter[/* willUpdate */7],
          /* shouldUpdate */counter[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "container jumbotron"
                        }, React.createElement("div", {
                              className: "row"
                            }, React.createElement("div", {
                                  className: "md-12 mx-auto"
                                }, React.createElement("center", undefined, React.createElement("h1", undefined, "This is a simple counter")))), React.createElement("div", {
                              className: "row md-5"
                            }), React.createElement("div", {
                              className: "row"
                            }, React.createElement("div", {
                                  className: "col-md-3"
                                }, ReasonReact.element(/* None */0, /* None */0, Decrementer$ReactTemplate.make((function () {
                                            return Curry._1(self[/* send */3], /* Decrement */1);
                                          }), /* array */[]))), React.createElement("div", {
                                  className: "col-md-6"
                                }, React.createElement("center", undefined, React.createElement("h1", undefined, String(self[/* state */1][/* count */0])))), React.createElement("div", {
                                  className: "col-md-3"
                                }, ReasonReact.element(/* None */0, /* None */0, Incrementer$ReactTemplate.make((function () {
                                            return Curry._1(self[/* send */3], /* Increment */0);
                                          }), /* array */[])))));
            }),
          /* initialState */(function () {
              return /* record */[/* count */5];
            }),
          /* retainedProps */counter[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] - 1 | 0]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] + 1 | 0]]);
              }
            }),
          /* subscriptions */counter[/* subscriptions */13],
          /* jsElementWrapped */counter[/* jsElementWrapped */14]
        ];
}

exports.counter = counter;
exports.make = make;
/* counter Not a pure module */
