// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var incrementer = ReasonReact.statelessComponent("Incrementer");

function make(handleClick, _) {
  return /* record */[
          /* debugName */incrementer[/* debugName */0],
          /* reactClassInternal */incrementer[/* reactClassInternal */1],
          /* handedOffState */incrementer[/* handedOffState */2],
          /* willReceiveProps */incrementer[/* willReceiveProps */3],
          /* didMount */incrementer[/* didMount */4],
          /* didUpdate */incrementer[/* didUpdate */5],
          /* willUnmount */incrementer[/* willUnmount */6],
          /* willUpdate */incrementer[/* willUpdate */7],
          /* shouldUpdate */incrementer[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("button", {
                          className: "btn btn-success btn-block",
                          onClick: handleClick
                        }, "+");
            }),
          /* initialState */incrementer[/* initialState */10],
          /* retainedProps */incrementer[/* retainedProps */11],
          /* reducer */incrementer[/* reducer */12],
          /* subscriptions */incrementer[/* subscriptions */13],
          /* jsElementWrapped */incrementer[/* jsElementWrapped */14]
        ];
}

exports.incrementer = incrementer;
exports.make = make;
/* incrementer Not a pure module */
